/*
===============================================================================
DDL SCRIPT: Create Bronze Layer
===============================================================================

Script Purpose:
  This script creates tables in the 'bronze' schema, dropping existing tables 
  if they already exist.
  Run this script to re-define the DDL structure of the 'bronze' tables

===============================================================================
*/
